### ISSUE TITLE
about appium_lib

### ISSUE THREAD

**Issue by isnehc** [debugtalk/AppiumBooster#1]
“ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- appium_lib (LoadError)”
请问**appium_lib 这个是放关于appium包的？是哪些包？**
用GEM安装了appium_lib

**Comment by isnehc** [comment]
用GEM安装了appium_lib

**Comment by debugtalk** [comment]
appium_lib 是Appium的Ruby客户端，运行之前在项目根目录下 bundle install 就好了
