### ISSUE TITLE
运行ruby run.rb后 直接退出 initialize appium driver ...

### ISSUE THREAD

**Issue by isnehc** [debugtalk/AppiumBooster#2]
在win7 android 环境下：
运行ruby run.rb后 直接退出 initialize appium driver ... 
这是为什么呢？
－－运行目录需要设置下

**Comment by isnehc** [comment]
Expected：这个值取的是什么？ 
如果有H5的页面，也是可以直接套用的嘛？

**Comment by debugtalk** [comment]
Expected 对应的是预期结果检测，也填写控件的ID。相当于通过判断控件是否存在，来确定页面是否正常跳转。

**Comment by debugtalk** [comment]
你运行ruby run.rb后直接退出，模拟器有启动么？把堆栈信息贴出来看下。

**Comment by isnehc** [comment]
@debugtalk 运行 ruby run.rb 后直接退出解决了，是我没有设置好android目录。
那~如果有H5的页面，需要转成webview模式嘛？
对了，因为对ruby语言不了解，代码没有怎么看懂，思路很值学习，Ignore这为YES与为空值运行的效果是一样的，Ignore这个到Demo中起什么作用？
测试结果应该要保存下来，方便查看些

**Comment by debugtalk** [comment]
@isnehc 当初加入Ignore参数的背景是这样的：例如某些账号有优惠券，登录系统后，会弹出优惠券的提示框；而有的账号没有优惠券，登录后就不会有这样的弹框。因此我通过对这类可能出现的步骤设置Ignore参数，结果就是，这类步骤不会影响到测试用例的执行结果。

当然，更好的做法应该是从测试数据着手，精确控制账号的状态。
